### ISSUE TITLE
interpolate() Error in approx(x = data_num[[1]], y = i, xout = seq(min(data_num[[1]]),  :    need at least two non-NA values to interpolate In addition: There were 29 warnings (use warnings() to see them)

### ISSUE THREAD

**Issue by Scott-S-Hannah** [fmmattioni/whippr#1]

**Comment by Scott-S-Hannah** [comment]
Hi Felipe, 

Have been giving whippr a test run but am having an issue with the interpolate function. I've attached the file I was testing it on. 

> df %>% 
interpolate()

Error in approx(x = data_num[[1]], y = i, xout = seq(min(data_num[[1]]),  : 
  need at least two non-NA values to interpolate
In addition: There were 29 warnings (use warnings() to see them)

> warnings()
Warning messages:
1: In regularize.values(x, y, ties, missing(ties)) :
  collapsing to unique 'x' values
[test_file.xlsx](https://github.com/fmmattioni/whippr/files/4496926/test_file.xlsx)

**Comment by fmmattioni** [comment]
Hi Scott! Thank you very much for trying it out and reporting this issue. I have just looked into it, and I added a fix here https://github.com/fmmattioni/whippr/commit/841ad2a3838161354779b1832c079727fe569b90.

It should work now.

Best,
Felipe

**Comment by Scott-S-Hannah** [comment]
Perfect! Works a treat now. The read data function alone is an immense help.
