### ISSUE TITLE
Error in read_data.parvo(): object 'V2' not found

### ISSUE THREAD

**Issue by marikaecarr** [fmmattioni/whippr#14]
Hi there, I am attempting to run a script that I wrote a while ago to use whippr to analyse ventilatory thresholds locally per your paper/app, in addition to VO2peak values for my thesis. 

It previously ran successfully on this file on 2023-02-20 with whippr_0.1.2 but seems to have run into issues with the latest version.

I tried to run this:

path <- "C:/Users/Username/Downloads/FileName.xlsx" #I have changed path details (folders and filenames) before posting
df_t <- read_data(path = path, metabolic_cart = "parvo", time_column = "t")

And got this error:

Error in `read_data.parvo()`:
! object 'V2' not found
Backtrace:
 1. whippr::read_data(path = path, metabolic_cart = "parvo", time_column = "t")
 2. whippr:::read_data.parvo(...)
 6. V2 %in% c(NA, "STPD", "BTPS")
Execution halted

It seems to be having issues around line 247/248 of read-data.R with the latest version (whippr_0.1.3). I have checked that I have the required packages attached, do you have any suggestions?

**Comment by fmmattioni** [comment]
can you please share this file with me so I can check it out?

**Comment by Jeffrothschild** [comment]
Hey Felipe, I'm now seeing the same issue. See attached for sample parvo file
[parvo test data.xlsx](https://github.com/user-attachments/files/16355049/parvo.test.data.xlsx)
Thanks
