### ISSUE TITLE
Average method can't be changed when performing a max.

### ISSUE THREAD

**Issue by marikaecarr** [fmmattioni/whippr#15]
Hi again!
I wanted to compare the effect of a few different bin sizes when using perform_max() for a sample of my dataset.
No matter what I do I can't change the ouput away from the default 30s bin-average, see output here:

<img width="461" alt="image" src="https://github.com/fmmattioni/whippr/assets/118340747/5c6b8706-2697-4a94-a4cc-c411554e9e80">

Looking at the function in: whippr/R/max.R I notice:
<img width="338" alt="image" src="https://github.com/fmmattioni/whippr/assets/118340747/1eb34e90-549c-425d-8521-b225be197d3b">

I am a bit of a novice, so could be wrong, but I am wondering if the default behaviour you've documented has been hardcoded in these lines, overriding the normal behaviour of perform_average() ?

**Comment by fmmattioni** [comment]
thanks for reporting it.. a fix has just been pushed and you can install the latest version with `remotes::install_github("fmmattioni/whippr")`
