### ISSUE TITLE
vo2_kinetics() Error: Can't subset columns that don't exist.

### ISSUE THREAD

**Issue by Scott-S-Hannah** [fmmattioni/whippr#2]
Hi Felipe,

Was just testing the vo2_kinetics() with the data file in whippr and came across this issue.

# example file
path_example <- system.file("example_cosmed.xlsx", package = "whippr")

df <- read_data(path = path_example, metabolic_cart = "cosmed")

# vo2 kinetics test
results_kinetics <- vo2_kinetics(
  .data = df,
  intensity_domain = "moderate",
  time_column = "t",
  vo2_column = "VO2",
  protocol_n_transitions = 3,
  protocol_baseline_length = 360,
  protocol_transition_length = 360,
  cleaning_level = 0.95,
  cleaning_baseline_fit = c("linear", "exponential", "exponential"),
  fit_level = 0.95,
  fit_bin_average = 5,
  fit_phase_1_length = 20,
  fit_baseline_length = 120,
  fit_transition_length = 240,
  verbose = TRUE
)

────────────────────────────────  * V̇O₂ kinetics analysis *  ───────────────────────────────
✓ Detecting outliers
Error: Can't subset columns that don't exist.
x The column `.se.fit` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

> rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x The column `.se.fit` doesn't exist.
Backtrace:
  1. whippr::vo2_kinetics(...)
 45. vctrs:::stop_subscript_oob(...)
 46. vctrs:::stop_subscript(...)
Run `rlang::last_trace()` to see the full context.

> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x The column `.se.fit` doesn't exist.
Backtrace:
     █
  1. ├─whippr::vo2_kinetics(...)
  2. │ ├─whippr::detect_outliers(...)
  3. │ └─whippr:::detect_outliers.kinetics(...)
  4. │   └─`%>%`(...)
  5. │     ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  6. │     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  7. │       └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  8. │         └─whippr:::`_fseq`(`_lhs`)
  9. │           └─magrittr::freduce(value, `_function_list`)
 10. │             └─function_list[[i]](value)
 11. │               ├─dplyr::mutate(...)
 12. │               └─dplyr:::mutate.tbl_df(...)
 13. │                 └─dplyr:::mutate_impl(.data, dots, caller_env())
 14. ├─purrr::map2(...)
 15. │ └─whippr:::.f(.x[[i]], .y[[i]], ...)
 16. │   └─whippr::predict_bands(...)
 17. │     └─whippr::predict_bands_baseline(...)
 18. │       └─`%>%`(...)
 19. │         ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 20. │         └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 21. │           └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 22. │             └─whippr:::`_fseq`(`_lhs`)
 23. │               └─magrittr::freduce(value, `_function_list`)
 24. │                 └─function_list[[i]](value)
 25. │                   ├─dplyr::select(., x:.resid, -.se.fit)
 26. │                   └─dplyr:::select.data.frame(., x:.resid, -.se.fit)
 27. │                     └─tidyselect::vars_select(tbl_vars(.data), !!!enquos(...))
 28. │                       └─tidyselect:::eval_select_impl(...)
 29. │                         ├─tidyselect:::with_subscript_errors(...)
 30. │                         │ ├─base::tryCatch(...)
 31. │                         │ │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
 32. │                         │ │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 33. │                         │ │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
 34. │                         │ └─tidyselect:::instrument_base_errors(expr)
 35. │                         │   └─base::withCallingHandlers(...)
 36. │                         └─tidyselect:::vars_select_eval(...)
 37. │                           └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 38. │                             └─tidyselect:::eval_c(expr, data_mask, context_mask)
 39. │                               └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 40. │                                 └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 41. │                                   └─tidyselect:::as_indices_sel_impl(...)
 42. │                                     └─tidyselect:::as_indices_impl(x, vars, strict = strict)
 43. │                                       └─tidyselect:::chr_as_locations(x, vars)
 44. │                                         └─vctrs::vec_as_location(x, n = length(vars), names = vars)
 45. └─vctrs:::stop_subscript_oob(...)
 46.   └─vctrs:::stop_subscript(...)

**Comment by fmmattioni** [comment]
Hi Scott!

That is interesting.. I can't reproduce this error here:

``` r
library(whippr)

path_example <- system.file("example_cosmed.xlsx", package = "whippr")

df <- read_data(path = path_example, metabolic_cart = "cosmed")

results_kinetics <- vo2_kinetics(
  .data = df,
  intensity_domain = "moderate",
  time_column = "t",
  vo2_column = "VO2",
  protocol_n_transitions = 3,
  protocol_baseline_length = 360,
  protocol_transition_length = 360,
  cleaning_level = 0.95,
  cleaning_baseline_fit = c("linear", "exponential", "exponential"),
  fit_level = 0.95,
  fit_bin_average = 5,
  fit_phase_1_length = 20,
  fit_baseline_length = 120,
  fit_transition_length = 240,
  verbose = TRUE
)
#> ───────────────────────────────────────────  * V̇O₂ kinetics analysis *  ──────────────────────────────────────────
#> ✓ Detecting outliers
#> ● 14 outlier(s) found in transition 1
#> ● 15 outlier(s) found in transition 2
#> ● 13 outlier(s) found in transition 3
#> ✓ Processing data...
#> ✓       └─ Removing outliers
#> ✓       └─ Interpolating each transition
#> ✓       └─ Ensemble-averaging transitions
#> ✓       └─ Performing 5-s bin averages
#> ✓ Fitting data...
#> ✓       └─ Fitting baseline
#> ✓       └─ Fitting transition
#> ✓       └─ Calculating residuals
#> ✓       └─ Preparing plots
#> ────────────────────────────────────────────────────  * DONE *  ───────────────────────────────────────────────────

results_kinetics
#> # A tibble: 1 x 9
#>   data_outliers plot_outliers data_processed data_fitted model model_summary
#>   <list>        <list>        <list>         <list>      <lis> <list>       
#> 1 <tibble [757… <patchwrk>    <tibble [145 … <tibble [7… <nls> <tibble [4 ×…
#> # … with 3 more variables: model_residuals <list>, plot_model <list>,
#> #   plot_residuals <list>
```

<sup>Created on 2020-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It may be due to the `broom` package version you have.. Have you tried updating your packages? Let me know if that solves the problem and I will make sure this gets fixed when {whippr} is installed.

**Comment by Scott-S-Hannah** [comment]
broom was the culprit, thanks again! Package is looking great. 👍

**Comment by fmmattioni** [comment]
Sounds great! Thanks a lot for letting me know! :)
