### ISSUE TITLE
read_data() removes phase identifiers 

### ISSUE THREAD

**Issue by Scott-S-Hannah** [fmmattioni/whippr#4]
Hi Felipe 👋, 

Wondering if there is a way of retaining the data in the **Phase** column when importing with `read_data()`? Currently this seems to produce the column but replaces data with `NA`s. This also seems to be the case for the **Marker** column.

Thanks,
Scott

**Comment by fmmattioni** [comment]
Hi @Scott-S-Hannah!

I am sorry for my delayed response... I guess I know the problem, you are using data from the COSMED metabolic cart, correct?

**Comment by Scott-S-Hannah** [comment]
No problem, Felipe. 

Yes, it is the cosmed I am using. Thanks.

**Comment by fmmattioni** [comment]
Hey @Scott-S-Hannah,

I am really sorry again for my late reply.. In the end, I only had to change a single line of code. I was just quite busy with another project. Please, give it a try and let me know if that does not work.

**Comment by Scott-S-Hannah** [comment]
No problem, Felipe. Thanks for fixing that 👍🏻
