### ISSUE TITLE
vo2_max() and workload column option

### ISSUE THREAD

**Issue by Scott-S-Hannah** [fmmattioni/whippr#6]
Hi Felipe, 

It's me again... haha.

I was just trialing the new `vo2_max()` function and was wondering whether you would consider adding an option to use a pre-defined workload column? The `work_rate_magic` option is fantastic but I already have workrate column produced by the gas analyser.

p.s. your GitHub links on your packagedown site are leading to a [404 page](https://github.com/fmattioni/whippr/). I think there's an `M` missing from your GitHub account name 🤦‍♂️

Thanks,
Scott

**Comment by fmmattioni** [comment]
Hey Scott!

Thanks a lot for trying it out! Have you tried setting the `work_rate_column` argument in the `read_data()` function? Then you can set `work_rate_magic` to `FALSE` and that should do the trick. Let me know if it doesn't work.

I am going to update pkgdown, I hadn't noticed that before! Thank you!

**Comment by Scott-S-Hannah** [comment]
Hey Felipe, 

Thanks for the quick reply. Unfortunately, setting the `work_rate_column` in the `read_data()` function doesn't seem to change how the `vo2_max()` call works. 

I suppose if the `read_data()` function renamed my _Power_ column when importing to `"work_rate"`, then the `vo2_max()` function would produce peak power estimate. Another option might be to let users define their work_rate column like you have done with heart rate and rer etc.

```r
perform_max <- function(.data,
                        vo2_column = "VO2",
                        vo2_relative_column = NULL,
                        heart_rate_column = NULL,
                        rer_column = NULL,
                        workload_column = NULL,
                        average_method = c("bin", "rolling"),
                        average_length = 30,
                        plot = TRUE,
                        verbose = TRUE) {

  if (!is.null(workload_column))
    if (!workload_column %in% colnames(.data))
      stop(glue::glue("It looks like the column {workload_column} does not exist."),
           call. = FALSE)
  
  out <- dplyr::tibble(POpeak = ifelse(
    is.null(workload_column),
    as.integer(max(data_normalized[["work_rate"]])),
    as.interger(max(data_normalized[[workload_column]]))
  ))
  
}
``` 
Might this work? 

Thanks again, Felipe. You'll be pleased to know `whippr` is getting some good use in my thesis 😁.

**Comment by fmmattioni** [comment]
Oh, I see what the problem is.. I initially had an argument to specify the work rate column in `perfom_max()`, but ended up removing it to force it to be defined in `read_data()`. What I forgot to do is to rename the column you pass into `read_data()` as `work_rate`. I will push a fix.

It is great to hear that you are using it in your thesis!! If you have any suggestions, feel free to open a discussion in the Discussion tab! I am always looking for ways to improve the package.

**Comment by fmmattioni** [comment]
Hey Scott, I have just created a PR: https://github.com/fmmattioni/whippr/pull/7

Could you give it a try?

You can install it with: `remotes::install_github("fmmattioni/whippr#7")`

**Comment by Scott-S-Hannah** [comment]
Works a treat, Felipe. Thanks 🙌

**Comment by fmmattioni** [comment]
Thanks a lot for reporting it, Scott!
